# Example settings file for configuration purposes

LABOR_CONSTRAINT = 100
MACHINE_TIME_CONSTRAINT = 80
RAW_MATERIALS_CONSTRAINT = 70
P1_MAX_PRODUCTION = 20
P2_P3_MIN_COMBINED_PRODUCTION = 10
P4_MIN_PRODUCTION = 5
